### ISSUE TITLE
Refactor the Kubernetes Manifests to be CloudFormation layer resources

### ISSUE THREAD

**Issue by gargana** [aws-quickstart/quickstart-armory-enterprise#55]
Currently manifests for spinnaker deployment are combined into a single large manifests file.

I am proposing defining these as CloudFormation resources

ie:
```
apiVersion: v1
kind: Namespace
metadata:
  name: spinnaker
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: spin-sa
  namespace: spinnaker
---
...
```
Becomes:

```
SpinnakerNameSpace:
    Type: AWSQS::Kubernetes::Resource
    Properties:
      ClusterName: !Ref ClusterName
      Namespace: default
      Manifest: !Sub
        - |
          apiVersion: v1
          kind: Namespace
          metadata:
            name: spinnaker
 SpinnakerServiceAccount:
    Type: AWSQS::Kubernetes::Resource
    DependsOn: SpinnakerNameSpace
    Properties:
      ClusterName: !Ref ClusterName
      Namespace: spinnaker
      Manifest: !Sub
        - |
          apiVersion: v1
          kind: ServiceAccount
          metadata:
            name: spin-sa
            namespace: spinnaker
```
Refactoring these will allow for dependency management at the CloudFormation layer and allow us to surface problems with any particular manifest in isolation from the rest.

This should also allow for clean deletes and resolve : #53
